import { TypescriptDeclarations, TypescriptModulesFactory } from "./typescript";
import { LocalFiles } from "./static_declarations";
import { DictionaryState, ListState, State } from "./state";
import { Scheme, Theme } from "./theme";
import { TransformedMessage } from "./message_transformation";
import { EditorBindings } from "./monaco";
import { LogEntry } from "./log";
import { LoadedLibraries } from "./library_fetching";
import { Diagnostic } from "./typescript/types";
export interface States {
    preferredColorScheme: State<Scheme>;
    activeTheme: State<Theme>;
    editorBindings: State<EditorBindings>;
    vimBindings: State<boolean>;
    messages: ListState<any>;
    transformedMessages: ListState<TransformedMessage>;
    rawLogs: ListState<LogEntry[]>;
    additionalData: State<any>;
    selectedMessageIndex: State<number>;
    scratchpadTexts: DictionaryState<string>;
    displayedScratchpadTexts: DictionaryState<number>;
    droppedFiles: State<LocalFiles>;
    query: State<any>;
    messageNotes: DictionaryState<string>;
    messageMarkers: DictionaryState<true>;
    libraryFetchingCodeTs: State<string>;
    libraryFetchingCodeJs: State<string>;
    dataFetchingCodeTs: State<string>;
    dataFetchingCodeJs: State<string>;
    transformationCodeTs: State<string>;
    transformationCodeJs: State<string>;
    libraries: State<LoadedLibraries>;
    libraryDeclarations: DictionaryState<TypescriptDeclarations>;
    libraryCodeTs: DictionaryState<string>;
    libraryCodeJs: DictionaryState<string>;
    libraryModules: State<TypescriptModulesFactory>;
    scriptDiagnostics: DictionaryState<Diagnostic[]>;
}
export default function init(): States;
